module.exports = {
  TASKS: {
    MESSAGE: 'MESSAGE',
    WAIT: 'WAIT',

    END_COURSE: 'END_COURSE',
    END_QUIZ: 'END_QUIZ',
  },

  ACTIONS: {
    USER_COMMAND_START: 'USER_COMMAND_START',
    USER_COMMAND_SUBSCRIBE: 'USER_COMMAND_SUBSCRIBE',
    USER_COMMAND_UNSUBSCRIBE: 'USER_COMMAND_UNSUBSCRIBE',
    USER_COMMAND_QUIZ: 'USER_COMMAND_QUIZ',
    USER_COMMAND_STOP: 'USER_COMMAND_STOP',
    USER_MESSAGE: 'USER_MESSAGE',
    SKIP_WAITING: 'SKIP_WAITING',
    RESPOND_WITH_NOT_FOUND: 'RESPOND_WITH_NOT_FOUND',
    RESPOND_WITH_HI: 'RESPOND_WITH_HI',
    RESPOND_WITH_PONG: 'RESPOND_WITH_PONG',
    RESPOND_WITH_DEFINITION: 'RESPOND_WITH_DEFINITION',
    RESPOND_WITH_IMAGE: 'RESPOND_WITH_IMAGE',
    RESPOND_WITH_AUDIO: 'RESPOND_AUDIO',
    RESPOND_WITH_EXAMPLES: 'RESPOND_WITH_EXAMPLES',
    RESPOND_WITH_SYNONYMS: 'RESPOND_WITH_SYNONYMS',
    RESPOND_WITH_IPA: 'RESPOND_WITH_IPA',
    RESPOND_WITH_TRANSLATION: 'RESPOND_WITH_TRANSLATION',
    RESPOND_WITH_QUIZ_ANSWER: 'RESPOND_WITH_QUIZ_ANSWER',
    RESPOND_WITH_COURSES: 'RESPOND_WITH_COURSES',
    RESPOND_WITH_QUIZZES: 'RESPOND_WITH_QUIZZES',
    RESPOND_WITH_SUBSCRIPTIONS: 'RESPOND_WITH_SUBSCRIPTIONS',

    ADD_TASKS_ON_TOP: 'ADD_TASKS_ON_TOP',
    ADD_TASKS: 'ADD_TASKS',
    MARK_COURSE_AS_FINISHED: 'MARK_COURSE_AS_FINISHED',

    SEND_MESSAGE: 'SEND_MESSAGE',

    TICK: 'TICK',
  },

  CONTEXTS: {
    DEFINITION: 'DEFINITION',
    QUIZ: 'QUIZ',
    TAKE_QUIZ: 'TAKE_QUIZ',
    SUBSCRIBE: 'SUBSCRIBE',
  },

  MESSAGE_CATEGORIES: {
    REQUEST: 'REQUEST',
    DEFINITION: 'DEFINITION',
    IMAGE: 'IMAGE',
    AUDIO: 'AUDIO',
    TRANSLATE: 'TRANSLATE',
    EXAMPLE: 'EXAMPLE',
    SYNONYMS: 'SYNONYMS',
    IPA: 'IPA',
    COURSES: 'COURSES',
    QUIZZES: 'QUIZZES',
    QUIZ: 'QUIZ',
    NEXT: 'NEXT',
    SKIP: 'SKIP',
    MORE: 'MORE',
    PING: 'PING',
    HI: 'HI',
    NO: 'NO',
    STOP: 'STOP',
    SUBSCRIPTION: 'SUBSCRIPTION',
    SUBSCRIBE: 'SUBSCRIBE',
  }
};
