module.exports = {
  TASKS: {
    LEARN: 'LEARN',
    WAIT_ANSWER: 'WAIT_ANSWER',
    END_COURSE: 'END_COURSE',
    QUIZ_QUESTION: 'QUIZ_QUESTION',
    END_QUIZ: 'END_QUIZ',
  },

  ACTIONS: {
    USER_COMMAND_START: 'USER_COMMAND_START',
    USER_COMMAND_SUBSCRIBE: 'USER_COMMAND_SUBSCRIBE',
    USER_COMMAND_UNSUBSCRIBE: 'USER_COMMAND_UNSUBSCRIBE',
    USER_COMMAND_QUIZZES: 'USER_COMMAND_QUIZZES',
    USER_COMMAND_QUIZ: 'USER_COMMAND_QUIZ',
    USER_COMMAND_STOP: 'USER_COMMAND_STOP',
    USER_MESSAGE: 'USER_MESSAGE',
    NEXT_LEARNING_TASK: 'NEXT_LEARNING_TASK',

    ADD_TASKS_ON_TOP: 'ADD_TASKS_ON_TOP',
    ADD_TASKS: 'ADD_TASKS',
    MARK_COURSE_AS_FINISHED: 'MARK_COURSE_AS_FINISHED',

    SEND_MESSAGE: 'SEND_MESSAGE',

    TICK: 'TICK'
  },
};
