module.exports = {
  TASKS: {
    LEARN: 'LEARN',
    WAIT_ANSWER: 'WAIT_ANSWER',
    END_COURSE: 'END_COURSE',
  },

  ACTIONS: {
    USER_COMMAND_START: 'USER_COMMAND_START',
    USER_COMMAND_SUBSCRIBE: 'USER_COMMAND_SUBSCRIBE',
    USER_COMMAND_UNSUBSCRIBE: 'USER_COMMAND_UNSUBSCRIBE',
    USER_MESSAGE: 'USER_MESSAGE',

    ADD_TASK_ON_TOP: 'ADD_TASK_ON_TOP',
    ADD_TASKS: 'ADD_TASKS',
    MARK_COURSE_AS_FINISHED: 'MARK_COURSE_AS_FINISHED',

    SEND_MESSAGE: 'SEND_MESSAGE',

    TICK: 'TICK'
  },
};
